ALTER TYPE "public"."api_key_management_action" ADD VALUE 'RENEWED';--> statement-breakpoint
ALTER TABLE "billing_checkout_sessions" ADD COLUMN "checkout_claim_hash" varchar(71);--> statement-breakpoint
ALTER TABLE "billing_checkout_sessions" ADD COLUMN "checkout_claim_expires_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "billing_checkout_sessions" ADD COLUMN "checkout_claim_consumed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "billing_checkout_sessions" ADD COLUMN "issued_api_key_id" uuid;--> statement-breakpoint
ALTER TABLE "billing_checkout_sessions" ADD CONSTRAINT "billing_checkout_sessions_issued_api_key_id_api_keys_id_fk" FOREIGN KEY ("issued_api_key_id") REFERENCES "public"."api_keys"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "billing_checkout_claim_hash_uidx" ON "billing_checkout_sessions" USING btree ("checkout_claim_hash") WHERE "billing_checkout_sessions"."checkout_claim_hash" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "billing_checkout_issued_api_key_uidx" ON "billing_checkout_sessions" USING btree ("issued_api_key_id") WHERE "billing_checkout_sessions"."issued_api_key_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "billing_checkout_sessions" ADD CONSTRAINT "billing_checkout_claim_shape_check" CHECK (("billing_checkout_sessions"."checkout_claim_hash" IS NULL AND "billing_checkout_sessions"."checkout_claim_expires_at" IS NULL AND "billing_checkout_sessions"."checkout_claim_consumed_at" IS NULL AND "billing_checkout_sessions"."issued_api_key_id" IS NULL) OR ("billing_checkout_sessions"."checkout_claim_hash" LIKE 'sha256:%' AND length("billing_checkout_sessions"."checkout_claim_hash") = 71 AND "billing_checkout_sessions"."checkout_claim_expires_at" IS NOT NULL AND "billing_checkout_sessions"."checkout_claim_expires_at" > "billing_checkout_sessions"."expires_at" AND "billing_checkout_sessions"."checkout_claim_expires_at" <= "billing_checkout_sessions"."expires_at" + interval '30 minutes' AND "billing_checkout_sessions"."checkout_claim_expires_at" <= "billing_checkout_sessions"."created_at" + interval '24 hours'));--> statement-breakpoint
ALTER TABLE "billing_checkout_sessions" ADD CONSTRAINT "billing_checkout_claim_consumption_check" CHECK (("billing_checkout_sessions"."checkout_claim_consumed_at" IS NULL AND "billing_checkout_sessions"."issued_api_key_id" IS NULL) OR ("billing_checkout_sessions"."checkout_claim_consumed_at" IS NOT NULL AND "billing_checkout_sessions"."issued_api_key_id" IS NOT NULL AND "billing_checkout_sessions"."checkout_claim_consumed_at" >= "billing_checkout_sessions"."created_at"));
