import { defineConfig, devices } from "@playwright/test";

function localPort(variable: string, fallback: number): number {
  const value = process.env[variable]?.trim();
  if (!value) return fallback;
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed) || parsed < 1_024 || parsed > 65_535) {
    throw new Error(`${variable} must be a local non-privileged TCP port`);
  }
  return parsed;
}

const publicPort = localPort("PLAYWRIGHT_PUBLIC_PORT", 3_000);
const opsPort = localPort("PLAYWRIGHT_OPS_PORT", 3_001);
if (publicPort === opsPort) throw new Error("Playwright public and ops ports must differ");

const publicBaseUrl = `http://127.0.0.1:${publicPort}`;
const opsBaseUrl = `http://127.0.0.1:${opsPort}`;
process.env.OPS_BASE_URL = opsBaseUrl;

const inheritedEnvironment = Object.fromEntries(
  Object.entries(process.env).filter(
    (entry): entry is [string, string] => typeof entry[1] === "string",
  ),
);

export default defineConfig({
  testDir: "./tests/e2e",
  fullyParallel: false,
  workers: 1,
  retries: process.env.CI ? 2 : 0,
  use: {
    baseURL: publicBaseUrl,
    trace: "retain-on-failure",
  },
  projects: [
    { name: "desktop", use: { ...devices["Desktop Chrome"] } },
    { name: "mobile", use: { ...devices["iPhone 13"], browserName: "chromium" } },
  ],
  webServer: [
    {
      name: "public",
      command: `pnpm exec next dev -p ${publicPort}`,
      url: publicBaseUrl,
      env: {
        ...inheritedEnvironment,
        APP_URL: publicBaseUrl,
        NEXT_DIST_DIR: `.next/playwright-public-${publicPort}`,
        TRENDSFAST_SURFACE: "public",
      },
      reuseExistingServer: false,
      timeout: 120_000,
    },
    {
      name: "ops",
      command: `pnpm exec next dev -p ${opsPort}`,
      url: `${opsBaseUrl}/ops`,
      env: {
        ...inheritedEnvironment,
        APP_URL: opsBaseUrl,
        // Delivery links generated by the ops surface must return to public.
        PUBLIC_APP_URL: publicBaseUrl,
        NEXT_DIST_DIR: `.next/playwright-ops-${opsPort}`,
        TRENDSFAST_SURFACE: "ops",
      },
      reuseExistingServer: false,
      timeout: 120_000,
    },
  ],
});
